//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos
    {
        public int id_Fotos { get; set; }
        public int id_Pueblo_magico { get; set; }
        public int id_Usuario { get; set; }
        public string foto { get; set; }
    
        public virtual pueblo_magico pueblo_magico { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
