//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstorial_atractivos
    {
        public int id_Atractivo { get; set; }
        public int id_Usuario { get; set; }
        public Nullable<double> promedio { get; set; }
    
        public virtual atractivo atractivo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
