//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion
    {
        public int id_Calificacion { get; set; }
        public int id_Atractivo { get; set; }
        public int id_Criterios_evaluacion { get; set; }
        public int id_Pueblo_magico { get; set; }
        public int id_Usuario { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public double calificacion1 { get; set; }
    
        public virtual atractivo_has_criterios_evaluacion atractivo_has_criterios_evaluacion { get; set; }
        public virtual historial_visitas historial_visitas { get; set; }
    }
}
