//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotos
    {
        public int id_Fotos { get; set; }
        public int id_Pueblo_magico { get; set; }
        public int id_Usuario { get; set; }
        public string foto { get; set; }
    
        public virtual pueblo_magico pueblo_magico { get; set; }
    }
}
