//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstorial_atractivos
    {
        public int id_Atractivo { get; set; }
        public int id_Usuario { get; set; }
        public Nullable<double> promedio { get; set; }
    
        public virtual atractivo atractivo { get; set; }
    }
}
